version: "3.8"
services:
  mongodb:
    container_name: 'mongodb-c'
    image: 'mongo'
    volumes:
      - data:/data/db
    #environment: 
      # - MONGO_INITDB_ROOT_USERNAME=max
      #MONGO_INITDB_ROOT_USERNAME: max
      #MONGO_INITDB_ROOT_PASSWORD: secret
    env_file: 
      - ./env/mongo.env
    # networks:
    #   - goals-net
    # docker compose creates network automatically.
    ports:
      - '27017:27017'
  backend:
    build: ./backend
    container_name: 'backend-c'
    # build: 
    #   context: ./backend
    #   dockerfile: dockerfile
    #   args: 
    #     some-arg: 1
    ports:
      - '2999:2888'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    environment: 
      - COMPOSE_DOCKER_CLI_BUILD=1
    env_file: 
      - ./env/backend.env
    depends_on: 
      - mongodb #this indicates to docker-compose to spin up this `service` first
  frontend:
    build: ./frontend
    container_name: 'frontend-c'
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    environment: 
      - COMPOSE_DOCKER_CLI_BUILD=1
    stdin_open: true # for using --it interactive mode
    tty: true # for using --it interactive mode
    depends_on:
      - backend
volumes: #named volumes should be put here.
  data:
  logs: