version: "3.8"
services:
  npm:
    build: ./
    stdin_open: true
    tty: true
    volumes:
      - ./:/app

# docker-compose command to run one service (including use of) & removing container after npm init
# docker-compose run --rm npm init